djangoapp/app/urls.py
from django.urls import path
from app.views import *
from app.scientist_views import *


app_name = 'app'

urlpatterns = [
    # app:index
    path('', index, name='index'),
    path('login_page/', login, name='login'),

    path('login_check/', login_check, name='login_check'),
    path('logout/', logout, name='logout'),

    # SCIENTIST URLS ----------------------------------------------------------------------

    #  create star
    path('create_star/', view_create_star, name='view_create_star'),
    path('pagina_erro/', view_create_star, name='pagina_erro'),
    path('pagina_sucesso/', view_create_star, name='pagina_sucesso'),

    # read star data
    path('read_star_data/', view_read_star_data, name='view_read_star_data'),
    path('star_report/', view_read_star_data, name='star_report'),
    path('pagina_erro/', view_read_star_data, name='pagina_erro'),

    # update star
    path('update_star/', view_update_star, name='view_update_star'),
    path('pagina_erro/', view_update_star, name='pagina_erro'),
    path('pagina_sucesso/', view_update_star, name='pagina_sucesso'),

    # delete star
    path('delete_star/', view_delete_star, name='view_delete_star'),
    path('pagina_erro/', view_delete_star, name='pagina_erro'),
    path('pagina_sucesso/', view_delete_star, name='pagina_sucesso'),

]

djangoapp/project/urls.py
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings
# from django.contrib import admin

urlpatterns = [
    path('', include('app.urls')),
    # path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

djangoapp/app/models.py
from django.db import models

# Create your models here.

# TABELAS

class Comunidade(models.Model):
    especie = models.OneToOneField('Especie', models.DO_NOTHING, db_column='especie', primary_key=True)  # The composite primary key (especie, nome) found, that is not supported. The first column is selected.
    nome = models.CharField(max_length=15, unique=True)
    qtd_habitantes = models.FloatField()

    class Meta:
        managed = True
        db_table = 'comunidade'
        unique_together = (('especie', 'nome'),)

class Dominancia(models.Model):
    planeta = models.ForeignKey('Planeta', models.DO_NOTHING, db_column='planeta')
    nacao = models.OneToOneField('Nacao', models.DO_NOTHING, db_column='nacao', primary_key=True)  # The composite primary key (nacao, planeta, data_ini) found, that is not supported. The first column is selected.
    data_ini = models.DateField()
    data_fim = models.DateField(blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'dominancia'
        unique_together = (('nacao', 'planeta', 'data_ini'),)


class Especie(models.Model):
    nome = models.CharField(primary_key=True, max_length=15)
    planeta_or = models.ForeignKey('Planeta', models.DO_NOTHING, db_column='planeta_or', blank=True, null=True)
    inteligente = models.CharField(max_length=1, blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'especie'


class Estrela(models.Model):
    id_estrela = models.CharField(primary_key=True, max_length=31)
    nome = models.CharField(max_length=31, blank=True, null=True)
    classificacao = models.CharField(max_length=31, blank=True, null=True)
    massa = models.FloatField(blank=True, null=True)
    x = models.FloatField()
    y = models.FloatField()
    z = models.FloatField()

    class Meta:
        managed = True
        db_table = 'estrela'
        unique_together = (('x', 'y', 'z'),)


class Faccao(models.Model):
    nome = models.CharField(primary_key=True, max_length=15)
    lider = models.OneToOneField('Lider', models.DO_NOTHING, db_column='lider')
    ideologia = models.CharField(max_length=15, blank=True, null=True)
    qtd_nacoes = models.FloatField(blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'faccao'


class Federacao(models.Model):
    nome = models.CharField(primary_key=True, max_length=15)
    data_fund = models.DateField()

    class Meta:
        managed = True
        db_table = 'federacao'


class Habitacao(models.Model):
    planeta = models.OneToOneField('Planeta', models.DO_NOTHING, db_column='planeta', primary_key=True)  # The composite primary key (planeta, especie, comunidade, data_ini) found, that is not supported. The first column is selected.
    especie = models.ForeignKey(Comunidade, models.DO_NOTHING, db_column='especie')
    comunidade = models.ForeignKey(Comunidade, models.DO_NOTHING, db_column='comunidade', to_field='nome', related_name='habitacao_comunidade_set')
    data_ini = models.DateField()
    data_fim = models.DateField(blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'habitacao'
        unique_together = (('planeta', 'especie', 'comunidade', 'data_ini'),)


class Lider(models.Model):
    cpi = models.CharField(primary_key=True, max_length=14)
    nome = models.CharField(max_length=15, blank=True, null=True)
    cargo = models.CharField(max_length=10)
    nacao = models.ForeignKey('Nacao', models.DO_NOTHING, db_column='nacao')
    especie = models.ForeignKey(Especie, models.DO_NOTHING, db_column='especie')

    class Meta:
        managed = True
        db_table = 'lider'


class Nacao(models.Model):
    nome = models.CharField(primary_key=True, max_length=15)
    qtd_planetas = models.FloatField(blank=True, null=True)
    federacao = models.ForeignKey(Federacao, models.DO_NOTHING, db_column='federacao', blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'nacao'


class NacaoFaccao(models.Model):
    nacao = models.OneToOneField(Nacao, models.DO_NOTHING, db_column='nacao', primary_key=True)  # The composite primary key (nacao, faccao) found, that is not supported. The first column is selected.
    faccao = models.ForeignKey(Faccao, models.DO_NOTHING, db_column='faccao')

    class Meta:
        managed = True
        db_table = 'nacao_faccao'
        unique_together = (('nacao', 'faccao'),)


class OrbitaEstrela(models.Model):
    orbitante = models.OneToOneField(Estrela, models.DO_NOTHING, db_column='orbitante', primary_key=True)  # The composite primary key (orbitante, orbitada) found, that is not supported. The first column is selected.
    orbitada = models.ForeignKey(Estrela, models.DO_NOTHING, db_column='orbitada', related_name='orbitaestrela_orbitada_set')
    dist_min = models.FloatField(blank=True, null=True)
    dist_max = models.FloatField(blank=True, null=True)
    periodo = models.FloatField(blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'orbita_estrela'
        unique_together = (('orbitante', 'orbitada'),)


class OrbitaPlaneta(models.Model):
    planeta = models.OneToOneField('Planeta', models.DO_NOTHING, db_column='planeta', primary_key=True)  # The composite primary key (planeta, estrela) found, that is not supported. The first column is selected.
    estrela = models.ForeignKey(Estrela, models.DO_NOTHING, db_column='estrela')
    dist_min = models.FloatField(blank=True, null=True)
    dist_max = models.FloatField(blank=True, null=True)
    periodo = models.FloatField(blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'orbita_planeta'
        unique_together = (('planeta', 'estrela'),)


class Participa(models.Model):
    faccao = models.OneToOneField(Faccao, models.DO_NOTHING, db_column='faccao', primary_key=True)  # The composite primary key (faccao, especie, comunidade) found, that is not supported. The first column is selected.
    especie = models.ForeignKey(Comunidade, models.DO_NOTHING, db_column='especie')
    comunidade = models.ForeignKey(Comunidade, models.DO_NOTHING, db_column='comunidade', to_field='nome', related_name='participa_comunidade_set')

    class Meta:
        managed = True
        db_table = 'participa'
        unique_together = (('faccao', 'especie', 'comunidade'),)


class Planeta(models.Model):
    id_astro = models.CharField(primary_key=True, max_length=15)
    massa = models.FloatField(blank=True, null=True)
    raio = models.FloatField(blank=True, null=True)
    classificacao = models.CharField(max_length=63, blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'planeta'


class Sistema(models.Model):
    estrela = models.OneToOneField(Estrela, models.DO_NOTHING, db_column='estrela', primary_key=True)
    nome = models.CharField(max_length=31, blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'sistema'


class Users(models.Model):
    user_id = models.FloatField(primary_key=True)
    password = models.CharField(max_length=32, blank=True, null=True)
    id_lider = models.ForeignKey(Lider, models.DO_NOTHING, db_column='id_lider', blank=True, null=True)
    # id_lider = models.ForeignKey(Lider, on_delete=models.CASCADE)

    class Meta:
        managed = True
        db_table = 'users'

    # def __str__(self) -> str:
    #     return f"{self.user_id} | {self.id_lider}"


class LogTable(models.Model):
    user_id = models.ForeignKey(Users, on_delete=models.CASCADE)
    data_hora = models.DateTimeField(auto_now_add=True)
    message = models.CharField(max_length=50)

    class Meta:
        managed = True
        db_table = 'log_table'

    # def __str__(self):
    #     return f"{self.user_id} - {self.data_hora}"
    
# class Users(models.Model):
#     user_id = models.CharField(max_length=14)  # Assumindo que o CPF tem até 14 caracteres
#     password = models.CharField(max_length=50)
#     id_lider = models.ForeignKey(Lider, on_delete=models.CASCADE)

#     class Meta:
#         managed = True
#         db_table = 'users'

    # def __str__(self):
    #     return self.user_id

djangoapp/app/templates/app/cientista.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sistema de Gerenciamento - Cientista</title>
    <link rel="stylesheet" type="text/css" href="{% static 'app/css/cientista.css' %}">
</head>
<body>
    <h1>Sistema de Gerenciamento</h1>
    <div class="container">
        <div class="column">
            <fieldset>
                <legend>Funcionalidades - Cientista</legend>

                <!-- Inserir Estrela -->
                <h3>Criar Estrela</h3>
                <form method="post" action="{% url 'app:view_create_star' %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <div class="inline-inputs">
                            <div>
                                <label for="id_estrela">ID da Estrela:</label>
                                <input type="text" id="id_estrela" name="id_estrela" required>
                            </div>
                            <div>
                                <label for="nome">Nome:</label>
                                <input type="text" id="nome" name="nome" required>
                            </div>
                        </div>
                        <div class="inline-inputs">
                            <div>
                                <label for="classificacao">Classificação:</label>
                                <input type="text" id="classificacao" name="classificacao" required>
                            </div>
                            <div>
                                <label for="massa">Massa:</label>
                                <input type="text" id="massa" name="massa" required>
                            </div>
                        </div>
                        <div class="inline-inputs">
                            <div>
                                <label for="x">Coordenada x:</label>
                                <input type="text" id="x" name="x" required>
                            </div>
                            <div>
                                <label for="y">Coordenada y:</label>
                                <input type="text" id="y" name="y" required>
                            </div>
                            <div>
                                <label for="z">Coordenada z:</label>
                                <input type="text" id="z" name="z" required>
                            </div>
                        </div>
                        <button type="submit">CRIAR</button>
                    </div>
                </form>
                <br>

                <!-- Ler Estrela -->
                <h3>Ler Dados da Estrela</h3>
                <form method="post" action="{% url 'app:view_read_star_data' %}">
                    {% csrf_token %}
                    <!-- <label for="id_estrela">Nome da Estrela:</label> -->
                    <div class="form-group inline-inputs">
                        <label for="id_estrela">Nome da Estrela:</label>
                        <input type="text" id="id_estrela" name="estrela" class="read_placeholder" required>
                        <button type="submit">LER</button>
                    </div>
                    
                </form>
                <br>

                <!-- Atualizar Estrela -->
                <h3>Atualizar Estrela</h3>
                <form method="post" action="{% url 'app:view_update_star' %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <div class="inline-inputs">
                            <div>
                                <label for="id_estrela">ID da Estrela:</label>
                                <input type="text" id="id_estrela" name="id_estrela" required>
                            </div>
                            <div>
                                <label for="nome">Nome:</label>
                                <input type="text" id="nome" name="nome" required>
                            </div>
                        </div>
                        <div class="inline-inputs">
                            <div>
                                <label for="classificacao">Classificação:</label>
                                <input type="text" id="classificacao" name="classificacao" required>
                            </div>
                            <div>
                                <label for="massa">Massa:</label>
                                <input type="text" id="massa" name="massa" required>
                            </div>
                        </div>
                        <div class="inline-inputs">
                            <div>
                                <label for="x">Coordenada x:</label>
                                <input type="text" id="x" name="x" required>
                            </div>
                            <div>
                                <label for="y">Coordenada y:</label>
                                <input type="text" id="y" name="y" required>
                            </div>
                            <div>
                                <label for="z">Coordenada z:</label>
                                <input type="text" id="z" name="z" required>
                            </div>
                        </div>
                        <button type="submit">ATUALIZAR</button>
                    </div>
                </form>
                <br>

                <!-- Excluir Estrela -->
                <h3>Excluir Estrela</h3>
                <form method="post" action="{% url 'app:view_delete_star' %}">
                    {% csrf_token %}
                    <div class="form-group inline-inputs">
                        <label for="id_estrela">Nome da Estrela:</label>
                        <input type="text" id="id_estrela" name="estrela" class="delete_placeholder" required>
                        <button type="submit">EXCLUIR</button>
                    </div>
                </form>
                <br>
            </fieldset>
        </div>

        <div class="column">
            <fieldset>
                <legend>Relatórios</legend>

                <form method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <button type="submit">ESTRELA</button>
                    </div>
                </form>
                <br>

                <form method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <button type="submit">PLANETA</button>
                    </div>
                </form>
                <br>

                <form method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <button type="submit">SISTEMA</button>
                    </div>
                </form>
            </fieldset>
            <br>
            <form method="post" action="{% url 'app:logout' %}">
                {% csrf_token %}
                <button type="submit" class="report-button">SAIR</button>
            </form>
        </div>
    </div>
</body>
</html>

djangoapp/app/templates/app/cientista_lider_faccao.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cientista Lider Faccao</title>
</head>
<body>
    <h1>Cientista - Líder de Facção</h1>
</body>
</html>

djangoapp/app/templates/app/comandante.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sistema de Gerenciamento - Comandante</title>
    <link rel="stylesheet" type="text/css" href="{% static 'app/css/comandante.css' %}">
</head>

<body>
    <h1>Sistema de Gerenciamento</h1>
    <div class="container">
        <div class="column">
            <fieldset>
                <legend>Funcionalidades - Comandante</legend>

                <!-- Inserir Nação -->
                <h3>Incluir Nação</h3>
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group inline-inputs">
                        <div>
                            <label for="id_nacao">Nome da Nação:</label>
                            <input type="text" id="id_nacao" name="nacao" required>
                        </div>
                        <div>
                            <label for="id_federacao">Nome da Federação:</label>
                            <input type="text" id="id_federacao" name="federacao" required>
                        </div>
                    </div>
                    <button type="submit">INCLUIR</button>
                </form>
                <br><br>

                <!-- Excluir Nação -->
                <h3>Excluir Nação</h3>
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group inline-inputs">
                        <div>
                            <label for="id_nacao">Nome da Nação:</label>
                            <input type="text" id="id_nacao" name="nacao" required>
                        </div>
                        <div>
                            <label for="id_federacao">Nome da Federação:</label>
                            <input type="text" id="id_federacao" name="federacao" required>
                        </div>  
                    </div>
                    <button type="submit">EXCLUIR</button>
                </form>
                <br><br>

                <!-- Criar Nova Federação -->
                <h3>Criar Federação</h3>
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group inline-inputs">
                        <div>
                            <label for="id_nacao">Nome da Nação:</label>
                            <input type="text" id="id_nacao" name="nacao" required>
                        </div>
                        <div>
                            <label for="id_federacao">Nome da Nova Federação:</label>
                            <input type="text" id="id_federacao" name="federacao" required>
                        </div>
                    </div>
                    <button type="submit">CRIAR</button>
                </form>
                <br><br>

                <!-- Inserir Dominância -->
                <h3>Inserir Dominância</h3>
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group inline-inputs">
                        <div>
                            <label for="id_dom_planeta">Planeta:</label>
                            <input type="text" id="id_dom_planeta" name="dom_planeta" required>
                        </div>
                        <div>
                            <label for="id_dom_nacao">Nação:</label>
                            <input type="text" id="id_dom_nacao" name="dom_nacao" required>
                        </div>
                    </div>
                    <div class="form-group inline-inputs">
                        <div>
                            <label for="id_dom_data_ini">Data inicial:</label>
                            <input type="text" id="id_dom_data_ini" name="dom_data_ini" required>
                        </div>
                        <div>
                            <label for="id_dom_data_fim">Data final:</label>
                            <input type="text" id="id_dom_data_fim" name="dom_data_fim" required>
                        </div>
                    </div>
                    <button type="submit">INSERIR</button>
                </form>
                <br><br>
            </fieldset>
        </div>

        <div class="column">
            <!-- Gerar relatórios -->
            <fieldset>
                <legend>Relatórios</legend>
                <form method="post">
                    {% csrf_token %}
                    <button type="submit">GERAR RELATORIO</button>
                </form>
                <br><br>
            </fieldset>
            <br>
            <form method="post" action="{% url 'app:logout' %}">
                {% csrf_token %}
                <button type="submit" class="report-button">SAIR</button>
            </form>
        </div>
        
    </div>
</body>
</html>

djangoapp/app/templates/app/error_page.html
<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pagina Erro</title>
</head>
<h1>Ocorreu um Erro</h1>

<body>
    <hr>
    <br>
    <p style="font-size: large;">{{ mensagem }}</p>

    <br>
    <a href="javascript:history.go(-1)" style="font-size: large;">Voltar</a>
    <br><br>
</body>

</html>

djangoapp/app/templates/app/index.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sociedade Galactica</title>
    <link rel="stylesheet" type="text/css" href="{% static 'app/css/index.css' %}">
</head>
<body>
    <h1>Sociedade Galáctica</h1>
    <form method="post" action="{% url 'app:login' %}">
        {% csrf_token %}
        <button>LOGIN</button>
    </form>    
</body>
</html>

djangoapp/app/templates/app/login_page.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" type="text/css" href="{% static 'app/css/login_page.css' %}">
</head>

<body>
    <div class="page">
        <form method="post" class="formLogin" action="{% url 'app:login_check' %}">
            {% csrf_token %}
            <!-- <h1>Sociedade Galáctica</h1> -->
            <h1>Login</h1>
            <hr>
            <p>Digite os seus dados de acesso no campo abaixo.</p>

            <!-- Exibir mensagens de erro se houver -->
            {% if error_message %}
            <p class="error">{{ error_message }}</p>
            {% endif %}

            <div>
                <label for="cpi">CPI</label>
                <input type="text" name="cpi" placeholder="Digite seu CPI" autofocus="true" class="input-large" />
            </div>
            <br>
            <div>
                <label for="password">Senha</label>
                <input type="password" name="password" placeholder="Digite sua senha" class="input-large" />
                <br>
                <a href="/" class="forgot-password">Esqueci minha senha</a>
            </div>
            <!-- <br> -->
            <button type="submit">ACESSAR</button>
        </form>
      
        

    </div>
</body>
</html>

djangoapp/app/templates/app/oficial.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sistema de Gerenciamento - Oficial</title>
    <link rel="stylesheet" type="text/css" href="{% static 'app/css/oficial.css' %}">
</head>
<h1>Sistema de Gerenciamento</h1>

<body>

    <fieldset>
        <legend>Oficial</legend>
        <br>
        <div class="button-container">

            <div class="form-group">
                <label for="id_dom_data_ini">Data inicial:</label>
                <input type="text" id="id_dom_data_ini" name="dom_data_ini" required>
            </div>

            <div class="form-group">
                <label for="id_dom_data_fim">Data final:</label>
                <input type="text" id="id_dom_data_fim" name="dom_data_fim" required>
            </div>

            <br><br>
            <form method="post">
                {% csrf_token %}
                <button type="submit" class="report-button">ORDENAR POR SISTEMA</button>
            </form>
            <br>
            <form method="post">
                {% csrf_token %}
                <button type="submit" class="report-button">ORDENAR POR FACÇÃO</button>
            </form>
            <br>
            <form method="post">
                {% csrf_token %}
                <button type="submit" class="report-button">ORDENAR POR ESPÉCIE</button>
            </form>
            <br>
            <form method="post">
                {% csrf_token %}
                <button type="submit" class="report-button">ORDENAR POR PLANETA</button>
            </form>

        </div>
        <br>
    </fieldset>

    <br>
    <form method="post" action="{% url 'app:logout' %}">
        {% csrf_token %}
        <button type="submit" class="exit-button">SAIR</button>
    </form>
</body>
</html>

djangoapp/app/templates/app/oficial_lider_faccao.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Oficial Lider Faccao</title>
</head>
<body>
    <h1>Oficial - Líder de Facção</h1>
</body>
</html>

djangoapp/app/templates/app/star_report.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <title>Relatório de Estrelas</title>
    <link rel="stylesheet" type="text/css" href="{% static 'app/css/star_report.css' %}">
</head>
<body>
    <form method="post" action="{% url 'app:logout' %}">
        {% csrf_token %}
        <button type="submit" class="report-button">SAIR</button>
    </form>
    <a href="javascript:history.go(-1)" style="font-size: large;">Voltar</a>
    <h1>Relatório de Estrelas</h1>
    
    {% if result %}
    <table width="100%">
        <thead>
            <tr>
                <th width="14%">ID Estrela</th>
                <th width="14%">Nome</th>
                <th width="14%">Classificação</th>
                <th width="14%">Massa</th>
                <th width="14%">Coordenada X</th>
                <th width="14%">Coordenada Y</th>
                <th width="14%">Coordenada Z</th>        
            </tr>
        </thead>
        <tbody>
            {% for row in result %}
            <tr>
                <td>{{ row.0 }}</td>
                <td>{{ row.1 }}</td>
                <td>{{ row.2 }}</td>
                <td>{{ row.3 }}</td>
                <td>{{ row.4 }}</td>
                <td>{{ row.5 }}</td>
                <td>{{ row.6 }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
        <p>Nenhum dado encontrado.</p>
    {% endif %}
</body>
</html>

djangoapp/app/templates/app/success_page.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Página Sucesso</title>
</head>
    <h1>Sistema de Gerenciamento</h1>
<body>
    <hr>
    <br>
    <p style="font-size: large;">{{ mensagem }}</p>

    <br>
    <a href="javascript:history.go(-1)" style="font-size: large;">Voltar</a>
    <br><br>
    <form method="post" action="{% url 'app:logout' %}">
        {% csrf_token %}
        <button type="submit" class="report-button">SAIR</button>
    </form>
</body>
</html>